# -*- coding: utf-8 -*-
"""scorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3yf1iYeWU9uwODMd3P782xHzAfKseEQ
"""

def score_resume(jd_text, resume_text, skills_list):
    from keyword_extractor import extract_keywords

    results = extract_keywords(jd_text, resume_text, skills_list)

    final_score = results["skill_match_percent"]

    return {
        "required_skills": results["required_skills"],
        "preferred_skills": results["preferred_skills"],
        "resume_skills": results["resume_skills"],
        "required_found": results["required_found"],
        "required_missing": results["required_missing"],
        "preferred_found": results["preferred_found"],
        "preferred_missing": results["preferred_missing"],
        "skill_match_percent": final_score
    }

